# Generated by Django 5.2.15 on 2026-06-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text="Headline, e.g. 'Software Developer & Problem Solver'", max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('about', models.TextField(blank=True, help_text='Master summary; tailoring rewrites a copy of this.')),
                ('gdpr_text', models.TextField(blank=True, help_text='Recruitment-consent footer.')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Fixed fact.', max_length=255)),
                ('period', models.CharField(help_text="Fixed fact, e.g. '2022 — Present'", max_length=100)),
                ('description', models.TextField(help_text='Master prose; tailorable.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Fixed fact.', max_length=255)),
                ('tech', models.JSONField(blank=True, default=list, help_text='Fixed list of tech-chip strings.')),
                ('description', models.TextField(help_text='Master prose; tailorable.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Frameworks'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_categories', to='profiles.profile')),
            ],
            options={
                'verbose_name_plural': 'skill categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The chip text, e.g. 'FastAPI'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.skillcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
