# Generated by Django 5.2.15 on 2026-06-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tailoring', '0001_initial'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoredresume',
            name='posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored_resumes', to='tracker.jobposting'),
        ),
        migrations.AddField(
            model_name='tailoredresume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tailoring.resumetemplate'),
        ),
    ]
